openapi: 3.0.0
info:
  description: You can use this API to he access CXone Recording media and metadata. When playing back an interaction, the API transfers the interaction metadata and a link to the media file (voice-only and voice-and-screen media types) or the interaction metadata and the transcript (chat and email media types). When downloading, the API transfers a link to the media file.
  version: "V1"
  title: Media Playback API
  contact:
    email: 'R&DApiTeam@niceincontact.com' 
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: RecordingMediaPlayback
    description: The API returns interaction metadata and a link to the media file or the interaction metadata and the transcript.
paths:
  /media-playback/v1/contacts:
    get:
      tags:
        - Accessing the Recording Media
      summary: Access the full contact (the entire interaction with all segments) based on ACD Contact ID.
      description: Access the full contact (the entire interaction with all segments) based on ACD Contact ID. The ACD Contact ID depends on the ACD solution, for example, this is the same as the inContact Master Contact ID. Keep in mind that using the ACD Contact ID GET method, you can play back or download interactions recorded from December 13, 2018. Accessing an interaction recorded before December 13, 2018 will give an Interaction Not Found error.
      operationId: getACDContactRecordingData
      parameters:
        - name: acd-call-id
          in: query
          description: Unique identifier received from the ACD (the ACD Call ID depends on the ACD solution, for example, this is the same as the inContact Master Contact ID)
          required: true
          schema:
            type: string
        - name: media-type
          in: query
          description: Interaction type (such as voice-only, voice-and-screen, chat, email)
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - voice-only
                - voice-and-screen
                - chat
                - email
                - all
            default: all
            example:
              - all
        - name: exclude-waveforms
          in: query
          description: If your product does not display waveforms (sound waves) during playback, exclude them in the API to improve loading time. This parameter is only relevant for 'voice-only' or 'voice-and-screen' media types.
          required: false
          schema:
            type: boolean
            enum:
              - true
              - false
            default: true
        - name: isDownload
          in: query
          description: Download the media file for 'voice-only' and 'voice-and-screen' media types.
          required: false
          schema:
            type: boolean
            enum:
              - true
              - false
            default: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                $ref: '#/components/examples/InteractionExample'                 
        '400':
          description: 400 Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error400Example'
        '401':
          description: 401 Not Authorized to Play Back
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error401Example'
        '403':
          description: 403 Permissions Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error403Example'
        '404':
          description: 404 Interaction Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error404Example'
        '500':
          description: 500 Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error500Example'
  /media-playback/v1/acd-contacts/{acdContactId}/statements/{statementId}:
    get:
      tags:
        - Accessing the Recording Media
      summary: Access a recording statement based on ACD Contact ID and Statement ID.
      description: Access a recording statement based on ACD Contact ID and and Statement ID. The ACD Contact ID depends on the ACD solution, for example, this is the same as the inContact Master Contact ID.
      operationId: getDataToPlayByContactStatementId
      parameters:
        - name: acdContactId
          in: path
          description: Unique identifier received from the ACD (the ACD Contact ID depends on the ACD solution, for example, this is the same as the inContact Master Contact ID)
          required: true
          schema:
            type: string
        - name: statementId
          in: path
          description: Unique identifier of the recording statement
          required: true
          schema:
            type: string
        - name: media-type
          in: query
          description: Interaction type (such as voice-only, voice-and-screen, chat, email)
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - voice-only
                - voice-and-screen
                - chat
                - email
                - all
            default: all
            example:
              - all
        - name: isDownload
          in: query
          description: Download the media file for 'voice-only' and 'voice-and-screen' media types.
          required: false
          schema:
            type: boolean
            enum:
              - true
              - false
            default: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                $ref: '#/components/examples/InteractionExample'               
        '400':
          description: 400 Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error400Example'
        '401':
          description: 401 Not Authorized to Play Back
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error401Example'
        '403':
          description: 403 Permissions Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error403Example'
        '404':
          description: 404 Interaction Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error404Example'
        '500':
          description: 500 Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
              example:
                $ref: '#/components/examples/Error500Example'
components:
  examples:
    InteractionExample:
      value:
        contactId: 11e766de-4ace-33d0-9ff6-0242ac110004 
        Interactions:
          - Interaction:
              mediaType: voice-and-screen 
              
              startTime: '2018-11-20T08:20:31.941Z' 
              endTime: '2018-11-20T08:25:56.957Z' 
              data: 
                startTime: '2018-11-20T08:20:31.941Z' 
                endTime: '2018-11-20T08:25:56.957Z' 
                acwEndTime: '2018-11-20T08:27:09.643Z' 
                fileToPlayUrl: 'https://test-mcrplaybackmanager-4b5e-9234-54cbe7855ca1.mp4' 
                videoImageUrl: null 
                waveformDataList: 
                  - channel: 0  
                    normalizedPcmData:
                      - 0.001
                      - 0.001
                      - 0.001
                participantDataList: 
                  - participantType: AGENT 
                    agentName: Mary Walker 
                    participantId: '271863' 
                    userId: 11e846d2-dd9f-6f10-9aef-0242ac110002 
                    voiceStages: 
                      - stageType: ACTIVE 
                        startTime: '2018-11-20T08:20:31.941Z' 
                        endTime: '2018-11-20T08:25:56.957Z' 
                        recordingID: e079511b-c077-489e-85a3-24b1b147d3c7 
                        displays: null 
                    screenStages: 
                      - stageType: ACTIVE 
                        startTime: '2018-11-20T08:20:31.941Z' 
                        endTime: '2018-11-20T08:25:56.957Z' 
                        recordingID: e7621f2c-32e4-47cd-bfc5-29a48343f7e0 
                        displays: 
                          - width: 1680
                            height: 1050
                            topLeftX: -1680
                            topLeftY: 0
                          - width: 1680
                            height: 1050
                            topLeftX: 0
                            topLeftY: 0
                          - width: 1366
                            height: 768
                            topLeftX: 1680
                            topLeftY: 0
                    channel: 0 
                  - participantType: CUSTOMER 
                    agentName: null 
                    participantId: '68367118' 
                    userId: null 
                    voiceStages: 
                      - stageType: ACTIVE 
                        startTime: '2018-11-20T08:20:31.941Z' 
                        endTime: '2018-11-20T08:25:56.957Z' 
                        recordingID: e079511b-c077-489e-85a3-24b1b147d3c7 
                        displays: null 
                    screenStages: [] 
                    channel: 0 
                segmentsDataList: 
                  - startTime: '2018-11-20T08:20:31.941Z' 
                    endTime: '2018-11-20T08:25:56.957Z' 
                    acwEndTime: '2018-11-20T08:27:09.643Z' 
                    openReasonType: SEGMENT 
                    closeReasonType: SEGMENT 
                    directionType: OUTBOUND 
                    source: null 
                categoryMatchesList: 
                   - categoryHierarchy: 
                      - Account Inquiries 
                      - Account Problems 
                     secondsOffsets: 
                      - 24
                     confidence: 95 
                sentiments: 
                   - overallSentiment: POSITIVE
                     segmentStartTime: '2018-11-20T08:20:31.941Z' 
                     channel: 1 
                   - overallSentiment: POSITIVE 
                     segmentStartTime: '2018-11-20T08:20:31.941Z' 
                     channel: 0 
          - Interaction:
              mediaType: chat 
              startTime: '2018-11-21T08:27:09.643Z' 
              endTime: '2018-11-21T18:20:31.941Z' 
              data: 
                startTime: '2018-11-21T08:27:09.643Z' 
                endTime: '2018-11-21T18:20:31.941Z' 
                transferPoints: 
                  - '2018-11-21T10:34:23.433Z' 
                participants: 
                  - participantType: AGENT 
                    participantName: Kevin Allen 
                  - participantType: CUSTOMER 
                    participantName: '' 
                messages: 
                  - participantType: AGENT 
                    participantName: Kevin Allen 
                    text: agent 1 
                    timeStamp: '2018-11-21T10:35:23.643Z' 
                  - participantType: CUSTOMER 
                    participantName: '' 
                    text: Betty Alexander 
          - Interaction:
              mediaType: email 
              startTime: '2018-11-21T18:30:09.643Z' 
              endTime: '2018-11-21T18:36:36.347Z' 
              data: 
                startTime: '2018-11-21T18:30:09.643Z' 
                endTime: '2018-11-21T18:34:56.957Z' 
                acwEndTime: '2018-11-21T18:36:36.347Z' 
                participants: 
                  - participantType: AGENT 
                    participantName: Angela Bryant 
                    actions: 
                      - timeStamp: '2018-11-21T18:30:09.643Z' 
                        action: NewOutbound 
                      - timeStamp: '2018-11-21T18:34:56.957Z' 
                        action: Send 
                content: 
                  sentTime: '2018-11-21T18:34:56.957Z' 
                  from: doNotAnswer@ourcompany.com 
                  to: 
                    - angelab@yourcompany.com 
                  cc: [] 
                  bcc: [] 
                  subject: Hello 
                  body: Hi 
    Error400Example:
      value:
        internalCode: 8100
        message: Invalid request.
    Error401Example:
      value:
        internalCode: 8300
        message: This interaction is blocked due to compliance requirements.
    Error403Example:
      value:
        internalCode: 8500
        message: No permission to access this interaction.
    Error404Example:
      value:
        internalCode: 8200
        message: Interaction media not found.
    Error500Example:
      value:
        internalCode: 8400
        message: Internal server error.
    DownloadMediaExample:
      value:
        redirectUrl: 'https://test-mcrplaybackmanager-1sb9i02hff9vg.s3.us-west-2.amazonaws.com/perm_rp_test_withacd12294598/output_815728d2-c619-42da-8b67-624a491bddc1_.mp4?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEL3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLXdlc3QtMiJHMEUCIE9QKtxSYIy0igPAnBOaYGfD0YDgpzJSKCya47uOfnF9AiEAkyOIFTDHZq59lgh6jgpkD0i96frlBKuPQTfDY6Dd3Kkq%2BgMIVhADGgw5MzQxMzcxMzI2MDEiDCthLn5NdHvytuQ2XirXA02Gi4d6T7Cu9u0bm8IJ18W9dDfizxra%2BivfEOtNAXZfjkgsSz22FmHgTzqXtd2TR1%2BxaT9V%2BbqBcWP4Vzr0CQct%2FjZRZP0t5MBCMjY2EdLhkMDjZxAhgFhuILYQdA6JsnaJcsXuIhmmzdrRBJjLQYuC3wFSo6%2BqqWLCACeKIOtLRQrkHWBb3vvGggr5atmZqCDjBZUlpIqi0SsrHMfLAlZOhe0p4g93Pxvs1vyt02VZHa4Bz6qX%2FTO0eIK4orMN0OnU4sl29lNtvtiEQ0mdd0OUSnnMchWqtucK%2B08AhsTUhk%2FzyzVbmdEQiLye%2FLELVNj0crrp1Xm7erUKRMNBqk1%2B9SaPEEKNuQSa40ISl5AuaXzPcPheKJ8Km5%2FjqmG0YK%2Fm3SZZ4A5Z%2F2bZqT6VeqiPbKqjjfBQjzh%2FLWO3JRK33XJ40xnUmB9u4TmR6gSSE3TABdiMpPSSKp14ufoauEaglbyWHwhDLEcQPUEF%2FXCyt21Bs1jbF%2BOHAvEtvlyb%2FZrivn3vhZrZ4R24EfzMfiFVzzAfi0Ok1tLrqQiteJRdls3fyFHFE1SSpBc62gDaJroy67D5jp%2Brc5C%2Bn2%2FO7FD3dvYvs2dMl40IcZGc1SOowGRbadcsDzCJ6diLBjqlAdcQhzpTZfgV7KI0BXC8oaqsD2BcXwnEq%2B880IV8uSJ3iTwgTju8lLg9f2BVjWwjlMYldLzu9lyywD9inTsMdpiFNx5qzOL6q%2F0mE6TMzIqgum9M5tNppE5DgenKRQ55aiJsqldJTbdxxPArRNDRaePWD12eDREGvyi3JGxPcVaW5SwvvKPUgItMGykSL48EMssboJCIss2eii9l5y7Y0Qb0OnuzUw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20211025T053208Z&X-Amz-SignedHeaders=host&X-Amz-Expires=2700&X-Amz-Credential=ASIA5S7XJOY4VP4MDEJF%2F20211025%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=c721ba9c98aa54239afc23e941516f53cf657a3d4a84d09b4c3bde4afbddfc59'      
  schemas:
  
    categoryMatches:
      type: object
      properties:
        categoryHierarchy:
            type: array
            description: The list of the categories that was identified by QM Analytics 
            items:
              type: string
              description: The identified category
        
        secondsOffsets:
            type: array
            description: When the category was identified (time offset in seconds) from the start of the interaction
            items:
              type: number 
              format: int32
              
        confidence:
          type: number
          format: int32
          description: When QM Analytics identifies a category, the confidence in the match is defined as a percentage
    
    sentiment:
      type: object
      properties:
        overallSentiment:
          type: string
          enum:
           - POSITIVE
           - NEGATIVE
           - MIXED
           - NEUTRAL
          description: The sentiments that were identified for the segment, this parameter is only relevant for stereo recordings and is null if you don't have QM Analytics
          
        segmentStartTime:
          type: string
          format: date-time
          description: Time the segment started with the identified sentiment, configured according to ISO8601 RFC3339
          
        channel:
          type: integer
          format: int32
          description: Maps the sentiment to a specific audio channel
      
    segmentsData:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          description: Date and time the segment starts, configured according to ISO8601 RFC3339
        
        endTime:
          type: string
          format: date-time
          description: Date and time the segment ends, configured according to ISO8601 RFC3339
        
        acwEndTime:
          type: string
          format: date-time
          description: Date and time the After Call Work (ACW) ends, configured according to ISO8601 RFC3339
          
        openReasonType:
          type: string
          description: Why the segment was initiated 
          enum:
           - SEGMENT
           - TRANSFER
           - CONFERENCE
           
        closeReasonType:
          type: string
          description: Why the segment was ended 
          enum:
           - SEGMENT
           - TRANSFER
           - CONFERENCE
  
        directionType:
          type: string
          description: How the segment was initiated
          enum:
           - INBOUND
           - OUTBOUND
           - INTERNAL
           
        source:
          type: string
          nullable: true
          description: ACD source, such as inContact, Uptivity, 3rd recording solutions
    
        
    
    waveformData:
      type: object
      properties:
         channel:
          type: integer
          format: double
          description: Channel for the PCM data
          
         normalizedPcmData:
          type: array
          items:
            type: number
            format: double
            description: Normalized PCM data
            
    voiceStage:
      type: object
      properties:
        stageType:
          type: string
          description: The stage in audio recording
          enum:
           - ACTIVE
           - HOLD
           - MASK
           - TRANSFER
           
        startTime:
          type: string
          format: date-time
          description: Date and time the voice recording starts, configured according to ISO8601 RFC3339
          
        endTime:
          type: string
          format: date-time
          description: Date and time the voice recording ends, configured according to ISO8601 RFC3339
          
        recordingID:
          type: string
          format: uuid
          description: Parameter used internally by CXone
          
        displays:
          type: string
          nullable: true
          description: The configuration of the agent screens being recorded (size in pixels), this parameter is not used for voice recording
       
    
    displayProperties:
      type: object
      properties:
        width:
          type: integer
        height:
          type: integer
        topLeftX:
          type: integer
        topLeftY:
          type: integer
      
    screenStage:
      type: object
      properties:
        stageType:
          type: string
          description: The stage in screen recording
          enum:
           - ACTIVE
           - HOLD
           - MASK
           - TRANSFER
           
        startTime:
          type: string
          format: date-time
          description: Date and time the voice recording starts, configured according to ISO8601 RFC3339
          
        endTime:
          type: string
          format: date-time
          description: Date and time the voice recording ends, configured according to ISO8601 RFC3339
          
        recordingID:
          type: string
          format: uuid
          description: Parameter used internally by CXone
          
        displays:
          type: array
          description: Configuration of the agent screens being recorded (size in pixels)
          items:
             $ref: '#/components/schemas/displayProperties'
    
    VoiceAndScreenParticipant:
      type: object
      properties:
        participantType:
          type: string
          description: Type of participant
          enum:
           - AGENT
           - CUSTOMER
       
        agentName:
          type: string
          description: Name of the agent (null if the participantType is CUSTOMER)
        
        participantId:
          type: string
          description: Unique identifier of the participant (ACD participant ID)
          
        userId:
          type: string
          format: uuid
          description: Unique identifier of the agent (CXone user ID), this parameter is null if the participantType is CUSTOMER
          
        voiceStages:
          type: array
          description: The stage in audio recording
          items:
             $ref: '#/components/schemas/voiceStage'
             
        screenStages:
          type: array
          description: The stage in screen recording, this parameter is not used if the participantType is CUSTOMER
          items:
             $ref: '#/components/schemas/screenStage'
          
        channel:
          type: integer
          format: int32
          description: Maps the agent to a specific audio channel
          
    ChatParticipant:
      type: object
      properties:
        participantType:
          type: string
          description: Type of participant
          enum:
           - AGENT
           - CUSTOMER
        
        participantName:
          type: string
          description: Name of the participant, this parameter is null if the participantType is CUSTOMER
          
        screenStages:
          type: array
          description: The stage in screen recording, this parameter is not used if the participantType is CUSTOMER
          items:
             $ref: '#/components/schemas/screenStage'
      
      
    ChatMessages:
      type: object 
      properties:
        participantType:
          type: string
          description: Type of participant
          enum:
           - AGENT
           - CUSTOMER
        participantName:
          type: string
          description: Name of the participant, this parameter is null if the participantType is CUSTOMER
        text:
          type: string
          description: What is displayed in the chat for the name of the participant
        timeStamp:
          type: string
          format: date-time
          description: Timestamp of the specific message, configured according to ISO8601 RFC3339
          
    EmailActions:
      type: object
      properties:
       timeStamp:
         type: string
         format: date-time
         description: Timestamp of the email action, configured according to ISO8601 RFC3339
         
       action:
         type: string
         description: Email events
         enum:
           - Reply
           - NewOutbound
           - Transfer
           - Forward
           - Accept
           - Send
           
          
    EmailParticipant:
      type: object
      properties:
        participantType:
          type: string
          description: Type of participant
          enum:
            - AGENT
            - CUSTOMER
                
        participantName:
          type: string
          description: Name of the participant
          
        actions:
          type: array
          description: Email events
          items:
             $ref: '#/components/schemas/EmailActions'
             
        screenStages:
          type: array
          description: The stage in screen recording, this parameter is not used if the participantType is CUSTOMER
          items:
             $ref: '#/components/schemas/screenStage'

        content:
          type: object
          properties:
            sentTime:
              type: string
              format: date-time
              description: Date and time the email was sent, configured according to ISO8601 RFC3339
            from: 
              type: string
              format: email
              description: The sender's email address
            to: 
              type: array
              items:
                type: string
                format: email
                description: The addressee's email address
            cc: 
              type: array
              items:
                type: string
                format: email
                description: Email address of contacts copied on the email
            bcc: 
              type: array
              items:
                type: string
                format: email
                description: Email address of contacts blindly copied on the email
          
            subject:
              type: string    
              description: Subject of the email
            
            body:
              type: string 
              description: Body of the email
              
    VoiceAndScreen:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          description: Date and time the interaction starts, configured according to ISO8601 RFC3339
        endTime:
          type: string
          format: date-time
          description: Date and time the interaction ends, configured according to ISO8601 RFC3339
        acwEndTime:
          type: string
          format: date-time
          description: Date and time the After Call Work (ACW) ends, configured according to ISO8601 RFC3339
        fileToPlayUrl:
          type: string
          format: uri
          description: The temporary media storage location (URL)
        videoImageUrl:
          type: string
          format: uri
          description: Poster (the first frame of the video), this parameter is typically null
        waveformDataList:
          type: array
          description: Normalized PCM data for each channel, used to visualize the waveforms (not applicable if the exclude-waveforms parameter is set to false)
          items:
            $ref: '#/components/schemas/waveformData' 
        participants:
          type: array
          description: The participants in the interaction
          items:
            $ref: '#/components/schemas/VoiceAndScreenParticipant'  
        segmentsDataList:
          type: array
          description: A segment is part of an interaction between one party and another, such as a customer and an agent
          items:
            $ref: '#/components/schemas/segmentsData'  
        categoryMatchesList:
          type: array
          description: The categories that were identified, this parameter is only relevant for stereo recordings and is null if you don't have QM Analytics 
          items:
            $ref: '#/components/schemas/categoryMatches'    
            
        sentiments:
          type: array
          description: The sentiments that were identified for the segment, this parameter is only relevant for stereo recordings and is null if you don't have QM Analytics
          items:
            $ref: '#/components/schemas/sentiment'
            
    Chat:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          description: Date and time the interaction starts, configured according to ISO8601 RFC3339
        endTime:
          type: string
          format: date-time
          description: Date and time the interaction ends, configured according to ISO8601 RFC3339
        acwEndTime:
          type: string
          format: date-time
          description: Date and time the After Call Work (ACW) ends, configured according to ISO8601 RFC3339
        fileToPlayUrl:
          type: string
          format: uri
          description: The temporary media storage location (URL)
        transferPoints:
          type: string
          format: date-time
          description: Time the chat was transferred to a different agent, configured according to ISO8601 RFC3339
        participants:
          type: array
          description: The participants in the interaction
          items:
            $ref: '#/components/schemas/ChatParticipant' 
        messages:
          type: array
          description: Each message in the chat, this is an array
          items:
            $ref: '#/components/schemas/ChatMessages' 
      
    Email:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          description: Date and time the interaction starts, configured according to ISO8601 RFC3339
        endTime:
          type: string
          format: date-time
          description: Date and time the interaction ends, configured according to ISO8601 RFC3339
        acwEndTime:
          type: string
          format: date-time
          description: Date and time the After Call Work (ACW) ends, configured according to ISO8601 RFC3339
        fileToPlayUrl:
          type: string
          format: uri
          description: The temporary media storage location (URL)
        participants:
          type: array
          description: The participants in the interaction
          items:
            $ref: '#/components/schemas/EmailParticipant'
      
    Interaction:
      type: object
      properties:
        mediaType:
          type: string
          description: Interaction type
          enum:
           - voice-only
           - voice-and-screen
           - chat
           - chat-and-screen
           - email
           - email-and-screen
           
        startTime:
          type: string
          format: date-time
          description: Date and time the interaction starts, configured according to ISO8601 RFC3339
          
        endTime:
          type: string
          format: date-time
          description: Date and time the interaction ends, configured according to ISO8601 RFC3339

        data:
          oneOf:
          - $ref: '#/components/schemas/VoiceAndScreen'
          - $ref: '#/components/schemas/Chat'
          - $ref: '#/components/schemas/Email'
          description: Interaction details
          
        '@type':
          type: string
          description: The media @type of the interaction (This attribute is automatically assigned)
          enum:
           - call
           - chat
           - email
          
    ApiResponse:
      type: object
      properties:
        contactId:
          type: string
          format: uuid
          description: Unique identifier of the contact (the entire interaction with all the segments)
        Interactions:
          type: array
          items:
            $ref: '#/components/schemas/Interaction'
            
    ApiResponseForDownload:
      type: object 
      properties:
        redirectUrl:
        type: string
        description: The temporary media storage location (URL) for download  
    ErrorApiResponse:
      type: object
      properties:
        internalCode:
          type: string
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
servers:
  - url: 'https://na1.nice-incontact.com'
    description: Production Environment (uses live data)
  - url: 'https://na1.test.nice-incontact.com'
    description: Test Environment
  - url: 'https://na1.dev.nice-incontact.com'
    description: Dev Environment
  - url: 'https://na1.staging.nice-incontact.com'
    description: Staging Environment
